version: '3.1'

services:

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: laravel
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: esw
    ports:
      - "3416:3306"